#!/usr/bin/env node
import fs from 'node:fs/promises';
import { spawnSync } from 'node:child_process';
import { ClipcaseError } from './errors.js';
import { loadConfig, writeConfig } from './config.js';
import { addEntry, createCase, ensureStore, exportCase, listCases, loadCase, searchCases } from './storage.js';
function usage(): string { return `clipcase — local-first Markdown casefiles\n\nUsage:\n  clipcase init [--storage <path>]\n  clipcase new <case> [--title <title>]\n  clipcase add <case> [--source <label>] [--tag <tag>] [--clipboard] [--allow-secret]\n  clipcase list\n  clipcase show <case>\n  clipcase search <query>\n  clipcase export <case> [--out <file>]\n`; }
type Parsed = { command?: string; positionals: string[]; flags: Map<string, string[]> };
function parse(argv: string[]): Parsed { const [command, ...rest] = argv; const flags = new Map<string, string[]>(); const positionals: string[] = []; for (let i = 0; i < rest.length; i++) { const token = rest[i]; if (token.startsWith('--')) { const eq = token.indexOf('='); const rawKey = token.slice(2, eq === -1 ? undefined : eq); const current = flags.get(rawKey) ?? []; if (eq !== -1) current.push(token.slice(eq + 1)); else if (['tag', 'source', 'title', 'storage', 'out'].includes(rawKey)) current.push(rest[++i] ?? ''); else current.push('true'); flags.set(rawKey, current); } else positionals.push(token); } return { command, positionals, flags }; }
function flag(parsed: Parsed, name: string): string | undefined { return parsed.flags.get(name)?.at(-1); }
function flagAll(parsed: Parsed, name: string): string[] { return (parsed.flags.get(name) ?? []).flatMap((value) => value.split(',')).map((value) => value.trim()).filter(Boolean); }
async function readStdin(): Promise<string> { if (process.stdin.isTTY) return ''; const chunks: Buffer[] = []; for await (const chunk of process.stdin) chunks.push(Buffer.from(chunk)); return Buffer.concat(chunks).toString('utf8'); }
function readClipboard(): string { const cmd = process.platform === 'darwin' ? 'pbpaste' : process.platform === 'win32' ? 'powershell.exe' : 'xclip'; const args = process.platform === 'win32' ? ['-NoProfile', '-Command', 'Get-Clipboard'] : process.platform === 'linux' ? ['-selection', 'clipboard', '-o'] : []; const result = spawnSync(cmd, args, { encoding: 'utf8' }); if (result.status !== 0) throw new ClipcaseError('Clipboard read failed; pipe text on stdin instead.', 4); return result.stdout; }
export async function run(argv = process.argv.slice(2)): Promise<void> { const parsed = parse(argv); if (!parsed.command || parsed.flags.has('help') || parsed.command === 'help') { console.log(usage()); return; } if (parsed.command === 'init') { const target = await writeConfig(flag(parsed, 'storage') ?? '.clipcase'); const config = await loadConfig(); await ensureStore(config.storageDir); console.log(`Initialized ${target}`); return; } const config = await loadConfig(); await ensureStore(config.storageDir); switch (parsed.command) { case 'new': { const name = parsed.positionals[0]; if (!name) throw new ClipcaseError('Missing case name.'); const meta = await createCase(config.storageDir, name, flag(parsed, 'title')); console.log(`Created case ${meta.name}`); break; } case 'add': { const name = parsed.positionals[0]; if (!name) throw new ClipcaseError('Missing case name.'); const text = parsed.flags.has('clipboard') ? readClipboard() : await readStdin(); if (!text.trim()) throw new ClipcaseError('No input text supplied on stdin or clipboard.'); const entry = await addEntry(config.storageDir, { caseName: name, text, source: flag(parsed, 'source') ?? 'stdin', tags: flagAll(parsed, 'tag'), allowSecret: parsed.flags.has('allow-secret') }); console.log(`Added ${entry.id} to ${entry.caseName}`); break; } case 'list': { const cases = await listCases(config.storageDir); if (parsed.flags.has('json')) console.log(JSON.stringify(cases, null, 2)); else for (const meta of cases) console.log(`${meta.name}\t${meta.entries.length}\t${meta.updatedAt}\t${meta.title}`); break; } case 'show': { const name = parsed.positionals[0]; if (!name) throw new ClipcaseError('Missing case name.'); console.log(JSON.stringify(await loadCase(config.storageDir, name), null, 2)); break; } case 'search': { const query = parsed.positionals.join(' '); if (!query) throw new ClipcaseError('Missing search query.'); const results = await searchCases(config.storageDir, query); if (parsed.flags.has('json')) console.log(JSON.stringify(results, null, 2)); else for (const result of results) console.log(`${result.caseName}\t${result.entry.id}\t${result.entry.source}\t${result.preview}`); break; } case 'export': { const name = parsed.positionals[0]; if (!name) throw new ClipcaseError('Missing case name.'); const body = await exportCase(config.storageDir, name); const out = flag(parsed, 'out'); if (out) { await fs.writeFile(out, body); console.log(`Exported ${name} to ${out}`); } else process.stdout.write(body); break; } default: throw new ClipcaseError(`Unknown command: ${parsed.command}\n\n${usage()}`); } }
run().catch((error: unknown) => { if (error instanceof ClipcaseError) { console.error(error.message); process.exit(error.exitCode); } console.error(error); process.exit(1); });
